# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: peterpanduro
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-http-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-http-api

provider:
  name: aws
  region: eu-north-1
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  weather:
    handler: functions/weather/handler.weather
    events:
      - httpApi:
          path: /weather
          method: get
